name: ExplosiveProjectiles
main: ExplosiveProjectiles\Loader
version: 1.0.0
api: 1.9.0
author: iksaku
# website: https://github.com/iksaku/ExplosiveProjectiles

permissions:
  explosiveprojectiles:
    default: op
    description: "Access to all the features!"
    children:
      explosiveprojectiles.commad:
        default: op
        description: "Enable or Disable explosive projectiles for you"
      explosiveprojectiles.arrows:
        default: op
        descriptiom: "Explosive Arrows!"
